server:
  port: 8083
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/archives}
  application:
    name: archivesservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
