server:
  port: 8082
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/todonotification}
  application:
    name: notificationservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
