server:
  port: 9000
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

















#spring:
#  application:
#    name: spring-cloud-api-gateway
#  main:
#    web-application-type: reactive
    #Specify how gateway will understand which request is going to be mapped to
    #which microservice, hence we need to perform route configuration, give the service names here
#  cloud:
#    gateway:
#      routes:
#        - id: user-authentication-service
#        - id: user-movie-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    fetchRegistry: true
#    registerWithEureka: true







